# Generated by Django 4.0.9 on 2023-02-25 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('sub_topic', models.CharField(max_length=30)),
                ('topic', models.CharField(max_length=30)),
                ('field', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans1', models.CharField(max_length=30)),
                ('ans2', models.CharField(max_length=30)),
                ('ans3', models.CharField(max_length=30)),
                ('ans4', models.CharField(max_length=30)),
                ('reason', models.CharField(max_length=500)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.question')),
            ],
        ),
    ]
